version: '3.7'

services:
  msyql:
    image: 'mysql:5.7'
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test-api-data
